title: Liz Mowrer
logo: /assets/img/headshot.jpeg
theme: jekyll-theme-minimal

head:
  - '<link rel="icon" type="image/png" href="/assets/img/bubble.png">'
  - '<link rel="apple-touch-icon" href="/assets/img/bubble.png">'
